### ISSUE TITLE
디렉터리와 파일 구분에 대한 이슈

### ISSUE THREAD

**Issue by FlyingChihwahwa** [seolmango/fileRenamer#3]
파일을 얻어낼 때 디렉터리가 따로 구분이 안됨니다... 대참사가 일어날 수도 있겠네요

**Comment by seolmango** [comment]
[해당 커밋](https://github.com/seolmango/fileRenamer/commit/5ecf5acdc8fc453de2ec1c8d08d10dad56e65720)

부로 해결되었습니다.
